name: 'GHA Sandbox'
description: 'GHA Sandbox'

inputs:
  token:
    description: 'A Personal Access token'
    required: true
  org:
    description: 'GitHub Organization identifier'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
